ignored = [
  "github.com/yahoo/yfuzz/pkg/schema",
  "github.com/yahoo/yfuzz/pkg/version",
]

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
